--4
create or replace trigger valid_data before insert or update on pracownicy_antoniak 
for each row 
begin
if :new.salary<0 then :new.salary:=0;
end if;

if :new.department_id <0 then :new.department_id:=80;
end if;

end;

update pracownicy_antoniak set salary =-10 where employee_id =1;
update pracownicy_antoniak set department_id= -10 where employee_id =1;

--5

create table errors_prac 
(id_oper NUMBER GENERATED by default on null as IDENTITY primary key
,operacja varchar2(200)
,nazwa_pola varchar2(200)
,opis_bledu varchar2(200)
,data_mod date
);


--insert into errors_prac values('','updating','salary','wartosc mniejsza niz 0',sysdate);



create or replace trigger report_errors before insert or update on pracownicy_antoniak
for each row 
begin
if updating and :new.salary<0 then insert into errors_prac values('','updating','salary','wartosc mniejsza niz 0',sysdate);
ELSIF updating and :new.department_id<0 then insert into errors_prac values('','updating','department_id','wartosc mniejsza niz 0',sysdate);
ELSIF inserting and :new.salary<0 then insert into errors_prac values('','inserting','salary','wartosc mniejsza niz 0',sysdate);
ELSIF inserting and :new.department_id<0 then insert into errors_prac values('','inserting','department_id','wartosc mniejsza niz 0',sysdate);
end if;
end;


--test
update pracownicy_antoniak set salary =-10 where employee_id =1;
update pracownicy_antoniak set department_id= -10 where employee_id =1;
insert INTO pracownicy_antoniak values(21,'robson','iui',sysdate,-100,-10,60);

--7

create or replace trigger zostaw_prezesa before delete on pracownicy_antoniak 
for each row 
begin
if :old.job_id like '%VP' or :old.job_id like '%PRES' then raise_application_error(-20001,'Zostaw prezesa'); 
end if;
end;

delete from pracownicy_antoniak where job_id like '%PRES';
delete from pracownicy_antoniak where job_id like '%VP';








